version: '3.5'

services:
  selenium-node-chrome:
    container_name: selenium-node-chrome
    image: selenium/node-chrome:4.20
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    networks:
      - application-network

  selenium-node-firefox:
    container_name: selenium-node-firefox
    image: selenium/node-firefox:4.20
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"
    networks:
      - application-network

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:4.20
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - application-network

networks:
  application-network:
    external: true
    name: flowmymoney
