/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package money.flowmy.testing;

public class App {
    public String getGreeting() {
        return "Automação E2E do flowmy.money";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
